// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6-zJhTT55cId10XVx4ADyDW4ynJzzMO8',
    appId: '1:1061190048687:web:a7e1485c0e6e8509326d5a',
    messagingSenderId: '1061190048687',
    projectId: 'filmbanisa',
    authDomain: 'filmbanisa.firebaseapp.com',
    storageBucket: 'filmbanisa.firebasestorage.app',
    measurementId: 'G-78SNJVP665',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxIhTlt70doN6E-TnKzu4kcpiOVy1NCLk',
    appId: '1:1061190048687:android:a73582738e1c0455326d5a',
    messagingSenderId: '1061190048687',
    projectId: 'filmbanisa',
    storageBucket: 'filmbanisa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-JoMF8SZk3u2TEY1Q3JGw7vPpGYhw3XQ',
    appId: '1:1061190048687:ios:0ee2728d9ec0f69a326d5a',
    messagingSenderId: '1061190048687',
    projectId: 'filmbanisa',
    storageBucket: 'filmbanisa.firebasestorage.app',
    iosBundleId: 'com.example.filmbanisa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-JoMF8SZk3u2TEY1Q3JGw7vPpGYhw3XQ',
    appId: '1:1061190048687:ios:0ee2728d9ec0f69a326d5a',
    messagingSenderId: '1061190048687',
    projectId: 'filmbanisa',
    storageBucket: 'filmbanisa.firebasestorage.app',
    iosBundleId: 'com.example.filmbanisa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6-zJhTT55cId10XVx4ADyDW4ynJzzMO8',
    appId: '1:1061190048687:web:7cbbf88368355171326d5a',
    messagingSenderId: '1061190048687',
    projectId: 'filmbanisa',
    authDomain: 'filmbanisa.firebaseapp.com',
    storageBucket: 'filmbanisa.firebasestorage.app',
    measurementId: 'G-WWWDHMTXCH',
  );
}
